[mongodb]
mongodb-dev.devdaws.site

[catalogue]
catalogue-dev.devdaws.site

[redis]
redis-dev.devdaws.site

[user]
user-dev.devdaws.site

[cart]
cart-dev.devdaws.site

[mysql]
mysql-dev.devdaws.site

[shipping]
shipping-dev.devdaws.site

[rabbitmq]
rabbitmq-dev.devdaws.site

[payment]
payment-dev.devdaws.site

[frontend]
frontend-dev.devdaws.site

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.devdaws.site
CATALOGUE_HOST=catalogue-dev.devdaws.site
REDIS_HOST=redis-dev.devdaws.site
USER_HOST=user-dev.devdaws.site
CART_HOST=cart-dev.devdaws.site
MYSQL_HOST=mysql-dev.devdaws.site
SHIPPING_HOST=shipping-dev.devdaws.site
RABBITMQ_HOST=rabbitmq-dev.devdaws.site
PAYMENT_HOST=payment-dev.devdaws.site